### ISSUE TITLE
dns_config: should probably look for dns instead

### ISSUE THREAD

**Issue by yeyeoke** [tale/headplane#29]
I'm trying to get Headplane to work with the new beta2, but I'm getting this error: 

2024-08-21T07:06:07.204Z (ERRO) [CFGX] Recieved invalid configuration file
2024-08-21T07:06:07.205Z (ERRO) [CFGX] The following schema issues were found:
2024-08-21T07:06:07.205Z (ERRO) [CFGX]   'dns_config': Required

It looks like Headplane is expecting **dns_config** to still be in the config, but it's now called **dns:**

As a sidenote, I believe that **acl_policy_path** might also need to be updated to work with later versions, the new format is: 

policy:
  mode: file
  path: "/etc/headscale/acl.json"

**Comment by Heavensong89** [comment]
I saw a post on the discord with a bit of a fix/workaround for now, thought it would be worth sharing here whilst waiting for a fix.

Add this to your headscale config.yaml

`dns_config: {}`

and set HEADSCALE_CONFIG_UNSTRICT to true

Also, I added an environment variable “ACL_FILE” so that I could still view/make changes to my ACL file from Headplane, as you say above, they fixed the issues with `policy.path` mapping now and removed `acl_policy_path`

This of course means no DNS functionality from within Headplane, but nice to have the UI back!

**Comment by tale** [comment]
I'll update the config ASAP.

**Comment by tale** [comment]
Fixed in `0.2.3`. The minimum requirement for Headscale is now `0.23.0-beta2` or else Headplane will start with errors.
