### ISSUE TITLE
Invalid API key shown in webpage for a valid API Key

### ISSUE THREAD

**Issue by posilan-alan** [tale/headplane#71]
Recently installed Headplane natively on existing Headscale deployment (also installed on the host os directly), I have had other GUIs that use APIKeys and these still function so headscale seems to be accepting and the key is valid. 

I have a reverse proxy setup in nginx but have tried sending to headscale direct as well, I have also tried with and without https.  

Login with sso also fails complaining  but I'm less concerned with this but there may be related root cause.

With debug logging all I see is 

2024-12-19T16:37:55.135Z (DEBG) [APIC] GET https://myserver.myfqdn.co.uk/api/v1/apikey
2024-12-19T16:37:56.671Z (DEBG) [APIC] GET https://lmyserver.myfqdn.co.uk/api/v1/apikey

I have provided a ROOT_API_KEY in the .env and I see during startup
"2024-12-19T16:52:34.025Z (DEBG) [CTXT] Checking ROOT_API_KEY and falling back to API_KEY" so this doesn't seem to be working either.

Any insight would be useful.

**Comment by detchenkov** [comment]
Hi, log message is a bit confusing, most likely it's linked to the cookies problem.
The one for ROOT_API_KEYS I would say it's normal as in fact in the code just after this message there will be a check if one of the two variables is defined.

I had the same problem, and it was because of cookies, in my case installation was done directly without passing by docker. In fact, it seems that even if you are using `LOAD_ENV_FILE=true` it will not load some of the variables. I passed by the environment variables and now it works. Here is how you can declare the variable in linux: `export COOKIE_SECRET=qwerty`

**Comment by posilan-alan** [comment]
>I passed by the environment variables and now it works. Here is how you can declare the variable in linux: `export COOKIE_SECRET=qwerty`

This worked like a charm, thank you very much for your help.

**Comment by posilan-alan** [comment]
Might be worth putting that in the documentation or checking why it doesn't get the variable but I'm happy with the work around.
